---
output: html_document
editor_options: 
  chunk_output_type: console
---



### Convenience Functions

```{r eval=TRUE}
library(ggraph)
```


#### Cleaning

```{r eval=TRUE, class.source = "fold-hide"}
clean_names <- function(n) {
  n[n == "DFA_alpha1_ExpMean"] <- "DFA α1 ExpMean"

  n[n == "DFA_alpha2_ExpMean"] <- "DFA α2 ExpMean"

  n[n == "DFA_alpha1_ExpRange"] <- "DFA α1 ExpRange"

  n[n == "DFA_alpha2_ExpRange"] <- "DFA α2 ExpRange"

  n[n == "DFA_alpha1_DimMean"] <- "DFA α1 DimMean"

  n[n == "DFA_alpha2_DimMean"] <- "DFA α2 DimMean"

  n[n == "DFA_alpha1_DimRange"] <- "DFA α1 DimRange"
  
  n[n == "DFA_alpha2_DimRange"] <- "DFA α2 DimRange"
  
  n[n == "DFA_alpha1"] <- "DFA α1"
  
  n[n == "DFA_alpha2"] <- "DFA α2"

  n[n == "CSI_Modified"] <- "CSI (modified)"

  n
}


assign_clusters <- function(table_clusters, data, clusters, col = "Hclust") {
  table_clusters[[col]] <- NA
  table_clusters[[col]][table_clusters$Index %in% row.names(data)] <- clusters
  table_clusters[[col]][table_clusters[[col]] == "0"] <- seq(length(unique(clusters)),sum(clusters == "0") + length(unique(clusters)) - 1)
  table_clusters
}


```

#### Dendrogram

```{r eval=TRUE, class.source = "fold-hide"}
plot_dendrogram <- function(model, clusters = NULL, points = TRUE, dis = NULL, ylim = -0.3, nudge_y = -0.02, angle = 90, h = NULL, edges = "elbow") {
  if(is.null(clusters)) {
    data <- tidygraph::as_tbl_graph(model)
  } else {
    data <- tidygraph::as_tbl_graph(model) %>% 
      tidygraph::activate(nodes) %>% 
      mutate(cluster = as.character(clusters[label]))
  }
  if(!is.null(dis)) {
    data <- data %>% 
      mutate(dis = dis[label])
  }
  
  # Tree
  p <- ggraph(data, layout = 'dendrogram', height = height)
    
  if(edges == "elbow") {
    p <- p + geom_edge_elbow()
  } else {
    p <- p + geom_edge_diagonal()
  }
    
    
  # Hline
  if(!is.null(h)) p <- p + geom_hline(yintercept = h, linetype = "dotted") 
  

  # Points
  if(points) {
    if(is.null(clusters)) {
      p <- p + geom_node_point(aes(filter=leaf))
    } else {
      p <- p + geom_node_point(aes(color = cluster, filter = leaf, size = dis))
    }
  }
  
  if(is.null(clusters)) {
    p <- p + geom_node_text(aes(label=label), angle = angle, hjust=1, nudge_y = nudge_y)
  } else {
    p <- p + geom_node_text(aes(label=label, color = cluster), angle = angle, hjust=1, nudge_y = nudge_y) +
      scale_colour_material_d(palette = "rainbow", guide = "none", na.value = "grey")
  }
 p + 
   ylim(ylim, NA) +
   theme_void()
}
```



#### Correlations

```{r eval=TRUE, class.source = "fold-hide"}
plot_correlation <- function(data, x = "Recording_Length", y = "RMSSD", xlab = x, ylab = y, color = "red", label = NULL) {
  data %>%
    ggplot(aes_string(x = x, y = y)) +
    geom_point2(size = 4, alpha = 0.66) +
    geom_smooth(method = "lm", formula = y ~ poly(x, 2), color = color, fill = color, alpha = 0.1, size = 1.5, se = FALSE) +
    annotate("label",
      x = min(data[[x]], na.rm = TRUE),
      y = max(data[[y]], na.rm = TRUE),
      label = label,
      hjust = 0
    ) +
    xlab(xlab) +
    ylab(ylab) +
    theme_modern() +
    ggside::geom_xsidedensity() +
    ggside::geom_ysidedensity() +
    ggside::scale_xsidey_continuous(breaks = NULL, labels = "", expand = expansion(c(0, 0))) +
    ggside::scale_ysidex_continuous(breaks = NULL, labels = "", expand = expansion(c(0, 0)))
}


plot_correlations <- function(data, r, color = NA) {
  r$label <- paste0(
      "r = ",
      insight::format_value(r$r),
      insight::format_p(r$p, stars_only = TRUE),
      ", ",
      insight::format_ci(r$CI_low, r$CI_high, r$CI, zap_small = TRUE)
    )
  r$xlab <- clean_names(r$Parameter1)
  r$ylab <- clean_names(r$Parameter2)
  
  ps <- list()
  for(i in 1:nrow(r)) {
    ps[[i]] <- plot_correlation(data, 
                                x = r$Parameter1[i], 
                                y = r$Parameter2[i], 
                                xlab = r$xlab[i], 
                                ylab = r$ylab[i], 
                                color = "red", 
                                label = r$label[i]) +
      theme(axis.title.x = element_blank())
  }
  
  ggpubr::ggarrange(plotlist = ps)
}
```




<!-- #### Cluster Analysis -->

<!-- ```{r eval=TRUE, class.source = "fold-hide"} -->
<!-- cluster_analysis <- function(x, -->
<!--                              n = NULL, -->
<!--                              method = "kmeans", -->
<!--                              include_factors = FALSE, -->
<!--                              standardize = TRUE, -->
<!--                              verbose = TRUE, -->
<!--                              distance_method = "euclidean", -->
<!--                              hclust_method = "complete", -->
<!--                              kmeans_method = "Hartigan-Wong", -->
<!--                              dbscan_eps = 15, -->
<!--                              iterations = 100, -->
<!--                              ...) { -->


<!--   # Sanity checks ----------------------------------------------------------- -->
<!--   insight::check_if_installed("performance") -->

<!--   # match arguments -->
<!--   method <- match.arg(method, choices = c("kmeans", "hkmeans", "pam", "pamk", "hclust", "dbscan", "hdbscan", "mixture"), several.ok = TRUE) -->

<!--   # Preparation ------------------------------------------------------------- -->

<!--   # Preprocess data -->
<!--   data <- .prepare_data_clustering(x, include_factors = include_factors, standardize = standardize, ...) -->

<!--   # Get number of clusters -->
<!--   if (is.null(n) && any(method %in% c("kmeans", "hkmeans", "pam"))) { -->
<!--     n <- tryCatch( -->
<!--       { -->
<!--         nc <- parameters::n_clusters(data, standardize = FALSE, ...) -->
<!--         n <- attributes(nc)$n -->
<!--         if (verbose) { -->
<!--           insight::print_color(sprintf("Using solution with %i clusters, supported by %i out of %i methods.\n", n, max(summary(nc)$n_Methods), sum(summary(nc)$n_Methods)), "blue") -->
<!--         } -->
<!--         n -->
<!--       }, -->
<!--       error = function(e) { -->
<!--         if (isTRUE(verbose)) { -->
<!--           stop(insight::format_message("Could not extract number of cluster. Please provide argument 'n'."), call. = FALSE) -->
<!--         } -->
<!--         2 -->
<!--       } -->
<!--     ) -->
<!--   } -->



<!--   # Apply clustering -------------------------------------------------------- -->


<!--   if (any(method == "kmeans")) { -->
<!--     rez <- .cluster_analysis_kmeans(data, n = n, kmeans_method = kmeans_method, iterations = iterations, ...) -->
<!--   } else if (any(method %in% c("hkmeans"))) { -->
<!--     rez <- .cluster_analysis_hkmeans(data, n = n, kmeans_method = kmeans_method, hclust_method = hclust_method, iterations = iterations, ...) -->
<!--   } else if (any(method %in% c("pam"))) { -->
<!--     rez <- .cluster_analysis_pam(data, n = n, distance_method = distance_method, ...) -->
<!--   } else if (any(method %in% c("pamk"))) { -->
<!--     rez <- .cluster_analysis_pamk(data, distance_method = distance_method, ...) -->
<!--   } else if (any(method %in% c("hclust"))) { -->
<!--     rez <- .cluster_analysis_hclust(data, n = n, distance_method = distance_method, hclust_method = hclust_method, iterations = iterations, ...) -->
<!--   } else if (any(method == "dbscan")) { -->
<!--     rez <- .cluster_analysis_dbscan(data, dbscan_eps = dbscan_eps, ...) -->
<!--   } else if (any(method == "hdbscan")) { -->
<!--     rez <- .cluster_analysis_hdbscan(data, ...) -->
<!--   } else if (any(method %in% c("mixture", "mclust"))) { -->
<!--     rez <- .cluster_analysis_mixture(data, ...) -->
<!--   } else { -->
<!--     stop("Did not find 'method' argument. Could be misspecified.") -->
<!--   } -->

<!--   # Assign clusters to observations -->
<!--   # Create NA-vector of same length as original data frame -->
<!--   clusters <- rep(NA, times = nrow(x)) -->
<!--   # Create vector with cluster group classification (with missing) -->
<!--   complete_cases <- stats::complete.cases(x[names(data)]) -->
<!--   clusters[complete_cases] <- rez$clusters -->

<!--   # Get clustering parameters -->
<!--   out <- model_parameters(rez$model, data = data, clusters = clusters, ...) -->
<!--   performance <- cluster_performance(out) -->

<!--   attr(out, "model") <- rez$model -->
<!--   attr(out, "method") <- method -->
<!--   attr(out, "clusters") <- clusters -->
<!--   attr(out, "data") <- data -->
<!--   attr(out, "performance") <- performance -->

<!--   class(out) <- c("cluster_analysis", class(out)) -->
<!--   out -->
<!-- } -->



<!-- # Clustering Methods -------------------------------------------------------- -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_kmeans <- function(data, n = 2, kmeans_method = "Hartigan-Wong", iterations = 100, ...) { -->
<!--   model <- stats::kmeans(data, centers = n, algorithm = kmeans_method, iter.max = iterations, ...) -->
<!--   list(model = model, clusters = model$cluster) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_hkmeans <- function(data, n = 2, kmeans_method = "Hartigan-Wong", hclust_method = "complete", iterations = 100, ...) { -->
<!--   insight::check_if_installed("factoextra") -->
<!--   model <- factoextra::hkmeans(data, k = n, km.algorithm = kmeans_method, iter.max = iterations, hc.method = hclust_method, ...) -->
<!--   list(model = model, clusters = model$cluster) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_pam <- function(data = NULL, n = 2, distance_method = "euclidean", ...) { -->
<!--   insight::check_if_installed("cluster") -->

<!--   model <- cluster::pam(data, k = n, metric = distance_method, ...) -->

<!--   list(model = model, clusters = model$clustering) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_pamk <- function(data = NULL, distance_method = "euclidean", pamk_method = "ch", ...) { -->
<!--   insight::check_if_installed("fpc") -->

<!--   model <- fpc::pamk(data, metric = distance_method, criterion = pamk_method, ...) -->

<!--   list(model = model$pamobject, clusters = model$pamobject$clustering) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_hclust <- function(data, n = 2, distance_method = "euclidean", hclust_method = "complete", iterations = 100, ...) { -->
<!--   if (is.null(n)) { -->
<!--     rez <- n_clusters_hclust(data, preprocess = FALSE, distance_method = distance_method, hclust_method = hclust_method, iterations = iterations, ...) -->
<!--     out <- list(model = attributes(rez)$model, clusters = rez$Cluster) -->
<!--   } else { -->
<!--     if (distance_method %in% c("correlation", "uncentered", "abscor")) { -->
<!--       warning(paste0("method '", distance_method, "' not supported by regular hclust(). Please specify another one or set n = NULL to use pvclust.")) -->
<!--     } -->
<!--     dist <- dist(data, method = distance_method, ...) -->
<!--     model <- stats::hclust(dist, method = hclust_method, ...) -->
<!--     out <- list(model = model, clusters = stats::cutree(model, k = n)) -->
<!--   } -->
<!--   out -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_dbscan <- function(data = NULL, dbscan_eps = 0.15, min_size = 0.1, borderPoints = FALSE, ...) { -->
<!--   insight::check_if_installed("dbscan") -->

<!--   if (min_size < 1) min_size <- round(min_size * nrow(data)) -->
<!--   model <- dbscan::dbscan(data, eps = dbscan_eps, minPts = min_size, borderPoints = borderPoints, ...) -->

<!--   list(model = model, clusters = model$cluster) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_hdbscan <- function(data = NULL, min_size = 0.1, ...) { -->
<!--   insight::check_if_installed("dbscan") -->

<!--   if (min_size < 1) min_size <- round(min_size * nrow(data)) -->
<!--   model <- dbscan::hdbscan(data, minPts = min_size, ...) -->

<!--   list(model = model, clusters = model$cluster) -->
<!-- } -->

<!-- #' @keywords internal -->
<!-- .cluster_analysis_mixture <- function(data = NULL, ...) { -->
<!--   insight::check_if_installed("mclust") -->

<!--   model <- mclust::Mclust(data, verbose = FALSE, ...) -->

<!--   list(model = model, clusters = model$classification) -->
<!-- } -->



<!-- # Methods ---------------------------------------------------------------- -->

<!-- #' @export -->
<!-- predict.cluster_analysis <- function(object, newdata = NULL, ...) { -->
<!--   if (is.null(newdata)) { -->
<!--     attributes(object)$clusters -->
<!--   } else { -->
<!--     NextMethod() -->
<!--   } -->
<!-- } -->


<!-- #' @export -->
<!-- print.cluster_analysis <- function(x, ...) { -->
<!--   NextMethod() -->

<!--   cat("\n") -->
<!--   print(attributes(x)$performance) -->

<!--   insight::print_color("\n# You can access the predicted clusters via 'predict()'.\n", "yellow") -->
<!--   invisible(x) -->
<!-- } -->




<!-- # Plotting ---------------------------------------------------------------- -->

<!-- #' @export -->
<!-- visualisation_recipe.cluster_analysis <- function(x, show_data = "text", type = "bars", ...) { -->
<!--   type <- match.arg(type, choices = c("bars", "centers")) -->

<!--   if (type == "bars") { -->
<!--     vr_cluster_bars(x, ...) -->
<!--   } else { -->
<!--     vr_cluster_centers(x, show_data = show_data, ...) -->
<!--   } -->
<!-- } -->



<!-- vr_cluster_bars <- function(x, ...) { -->
<!--   NULL -->
<!-- } -->



<!-- vr_cluster_centers <- function(x, show_data, ...) { -->
<!--   ori_data <- stats::na.omit(attributes(x)$data) -->
<!--   # Get 2 PCA Components -->
<!--   pca <- principal_components(ori_data, n = 2) -->
<!--   data <- stats::predict(pca) -->
<!--   names(data) <- c("x", "y") -->
<!--   data$Cluster <- as.character(stats::na.omit(attributes(x)$clusters)) -->

<!--   data$label <- row.names(ori_data) -->
<!--   if (!is.null(show_data) && show_data %in% c("label", "text")) { -->
<!--     label <- "label" -->
<!--   } else { -->
<!--     label <- NULL -->
<!--   } -->

<!--   # Centers data (also on the PCA scale) -->
<!--   data_centers <- stats::predict(pca, newdata = as.data.frame(x)[names(ori_data)], names = c("x", "y")) -->
<!--   data_centers$Cluster <- as.character(as.data.frame(x)$Cluster) -->

<!--   # Outliers -->
<!--   data$Cluster[data$Cluster == "0"] <- NA -->
<!--   data_centers <- data_centers[data_centers$Cluster != "0", ] -->

<!--   layers <- list() -->

<!--   # Layers ----------------------- -->

<!--   layers[["l1"]] <- list( -->
<!--     geom = show_data, -->
<!--     data = data, -->
<!--     aes = list(x = "x", y = "y", label = label, color = "Cluster") -->
<!--   ) -->

<!--   layers[["l2"]] <- list( -->
<!--     geom = "point", -->
<!--     data = data_centers, -->
<!--     aes = list(x = "x", y = "y", color = "Cluster"), -->
<!--     shape = "+", size = 10 -->
<!--   ) -->
<!--   layers[["l3"]] <- list( -->
<!--     geom = "labs", -->
<!--     x = "PCA - 1", -->
<!--     y = "PCA - 2", -->
<!--     title = "Clustering Solution" -->
<!--   ) -->

<!--   # Out -->
<!--   class(layers) <- c("visualisation_recipe", "see_visualisation_recipe", class(layers)) -->
<!--   attr(layers, "data") <- data -->
<!--   layers -->
<!-- } -->

<!-- #' @export -->
<!-- plot.cluster_analysis <- function(x, ...) { -->
<!--   plot(visualisation_recipe(x, ...)) -->
<!-- } -->
<!-- ``` -->


<!-- #### Utils -->
<!-- ```{r eval=TRUE, class.source = "fold-hide"} -->
<!-- .prepare_data_clustering <- function(x, include_factors = FALSE, standardize = FALSE, preprocess = TRUE, ...) { -->
<!--   if (preprocess == FALSE) { -->
<!--     return(x) -->
<!--   } -->

<!--   # Convert factors to numeric -->
<!--   # include factors? -->
<!--   if (include_factors) { -->
<!--     # ordered factors to numeric -->
<!--     factors <- sapply(x, is.ordered) -->
<!--     if (any(factors)) { -->
<!--       x[factors] <- sapply(x[factors], .factor_to_numeric) -->
<!--     } -->

<!--     # character and factors to dummies -->
<!--     factors <- sapply(x, function(i) is.character(i) | is.factor(i)) -->
<!--     if (any(factors)) { -->
<!--       dummies <- lapply(x[factors], .factor_to_dummy) -->
<!--       x <- cbind(x[!factors], dummies) -->
<!--     } -->
<!--   } else { -->
<!--     # remove factors -->
<!--     x <- x[sapply(x, is.numeric)] -->
<!--   } -->

<!--   # Remove all missing values from data, only use numerics -->
<!--   x <- stats::na.omit(x) -->
<!--   if (standardize == TRUE) { -->
<!--     x <- datawizard::standardize(x, ...) -->
<!--   } -->
<!--   x -->
<!-- } -->
<!-- ``` -->
