---
output: html_document
editor_options: 
  chunk_output_type: console
---


### Clustering


```{r, message=FALSE, warning=FALSE}
# Preprocessing
z <- effectsize::standardize(data[hrv_cols])
z <- datawizard::data_transpose(z)
z <- z[ , colSums(is.na(z)) < 0.2 * nrow(z)]  # keep only participants with few nans
z[is.na(z)] <- 0  # mean imputation
```


#### K-Means

##### How Many Clusters

```{r, message=FALSE, warning=FALSE}
set.seed(3)

n <- parameters::n_clusters(z, 
                            standardize = FALSE, 
                            package= c("NbClust", "easystats", "mclust"), 
                            nbclust_method = "average",
                            n_max = 10,
                            fast = FALSE)

n

plot(n)
```

##### 2-K Solution

```{r, message=FALSE, warning=FALSE}
set.seed(3)

rez <- parameters::cluster_analysis(z, standardize = FALSE, n = 2, method = "hkmeans")

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Kmeans_2")
```

##### 7-K Solution

```{r, message=FALSE, warning=FALSE}
set.seed(3)

rez <- parameters::cluster_analysis(z, standardize = FALSE, n = 7, method = "hkmeans")

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)


table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Kmeans_7")
```

##### 10-K Solution

```{r, message=FALSE, warning=FALSE}
set.seed(3)

rez <- parameters::cluster_analysis(z, n = 10, method = "hkmeans")

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Kmeans_10")
```


#### K-meloid
```{r, message=FALSE, warning=FALSE, cache = TRUE}
rez <- parameters::cluster_analysis(z, method = "pamk", distance_method = "manhattan")

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Kmeloid")
```

#### Hierarchial Clustering

##### Clustering (95\%)

```{r, message=FALSE, warning=FALSE, cache = TRUE}
set.seed(3)

# rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "hclust", distance_method = "correlation", hclust_method = "average", ci = 0.95, iterations = 2000)

rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "hclust", distance_method = "manhattan", hclust_method = "ward.D", ci = 0.95, iterations = 2000) # better fit R2 higher

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Hclust_95")
```



```{r, message=FALSE, warning=FALSE}
clusters <- table_clusters$Hclust_95
names(clusters) <- table_clusters$Index

library(ggraph)
plot_dendrogram(model = attributes(rez)$model$hclust, clusters = clusters, ylim=-1500, nudge_y = -100)
```

##### Clustering (90\%)

```{r, message=FALSE, warning=FALSE, cache = TRUE}
set.seed(3)

# rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "hclust", distance_method = "correlation", hclust_method = "average", ci = 0.90, iterations = 2000)

rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "hclust", distance_method = "manhattan", hclust_method = "ward.D", ci = 0.90, iterations = 2000) # better fit R2 higher


as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Hclust_90")
```



```{r, message=FALSE, warning=FALSE}
clusters <- table_clusters$Hclust_90
names(clusters) <- table_clusters$Index

plot_dendrogram(model = attributes(rez)$model$hclust, clusters = clusters, ylim=-1500, nudge_y = -100)
```

#### DBSCAN

##### Parameters Selection

```{r, message=FALSE, warning=FALSE}
n <- n_clusters_dbscan(z, standardize = FALSE, eps_range = c(0.1, 30), min_size = 2, method = "kNN")
plot(n)
```

##### DBSCAN

```{r, message=FALSE, warning=FALSE}
rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "dbscan", dbscan_eps = 10, min_size = 2, borderPoints = TRUE)

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "DBSCAN")
```

##### HDBSCAN

```{r, message=FALSE, warning=FALSE}
rez <- parameters::cluster_analysis(z, n = NULL, standardize = FALSE, method = "hdbscan", min_size = 2)

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)

table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "HDBSCAN")
```

#### Mixture Modelling


```{r, message=FALSE, warning=FALSE}
suppressMessages(library(mclust))
library(mclust)
rez <- parameters::cluster_analysis(z, method = "mixture")

as.data.frame(rez)[1:3]

insight::display(parameters::cluster_performance(rez))

plot(rez)


table_clusters <- assign_clusters(table_clusters, z, clusters = as.character(predict(rez)), col = "Mixture")
```
