on:
  push:
    branches:
      - main
  schedule:  # run every week
    - cron:  '0 0 * * 1'

name: Build

jobs:
  render:
    name: Generate documents
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - run: tlmgr --version
      - name: Install Core Dependencies
        run: |
            Rscript -e 'install.packages(c("rmarkdown", "remotes", "tidyverse", "insight", "bayestestR", "performance", "parameters", "effectsize", "modelbased", "correlation", "see", "ggrepel"))'
            Rscript -e 'remotes::install_github("easystats/report")'
            Rscript -e '# remotes::install_github("easystats/easystats")'
      - name: Install Other Dependencies
        run: |
            Rscript -e 'install.packages(c("qqplotr", "gridExtra"))'
      # The section below can be removed for added building speed on GitHub if you don't use Python
      - name: Install Python
        run: |
            Rscript -e "remotes::install_github('rstudio/reticulate')"
            Rscript -e "reticulate::install_miniconda()"
      - name: Render
        run: Rscript -e 'source("utils/render.R")'
      - name: Commit results
        run: |
          git commit README.md -m 'Build README.md' || echo "No changes to commit"
          git commit docs/index.html -m 'Build docs/index.html' || echo "No changes to commit"
          git commit word_and_pdf/SupplementaryMaterials.docx -m 'Build word_and_pdf/SupplementaryMaterials.docx' || echo "No changes to commit"
          git commit word_and_pdf/SupplementaryMaterials.pdf -m 'Build word_and_pdf/SupplementaryMaterials.pdf' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
